name: API Health Check

on:
  schedule:
    - cron: "* * * * *"  # Runs every minute
  workflow_dispatch:  # Allows manual triggering

jobs:
  check-api:
    runs-on: ubuntu-latest

    steps:
      - name: Make GET request
        run: |
          response=$(curl -s -o /dev/null -w "%{http_code}" https://sniplinkapp.onrender.com/)
          echo "HTTP Status: $response"
          if [ "$response" -ne 200 ]; then
            echo "API is down! Status: $response"
            exit 1
          fi
